language: java

jdk:
    - oraclejdk8

after_success:
- ./gradlew jacocoTestReport coveralls
- bash <(curl -s https://codecov.io/bash)
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
