language: java

jdk:
    - oraclejdk8

script: ./gradlew check --stacktrace

after_success:
- bash <(curl -s https://codecov.io/bash)
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
