server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jvm_bloggers
    username: jvm_bloggers
    password: jvm_bloggers
    driver: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1

# Mail Configuration
mailing:
  apiKey: "empty"
  fromEmail: "empty"

# Wicket configuration
wicket.core.settings.general.runtime-configuration: development
wicket.core.settings.debug.development-utilities-enabled: true
wicket.core.settings.debug.enabled: true
wicket.core.settings.debug.developmentUtilitiesEnabled: true
wicket.core.settings.debug.ajaxDebugModeEnabled: true
wicket.core.settings.debug.componentUseCheck: true

logging.level.com.jvm_bloggers: DEBUG

application.baseUrl: http://localhost:${server.port}

scheduler:
  publish-test-issue: 30000 # 30 seconds

facebook.api:
  userToken: #User access token can be created as it is described in FACEBOOK.md
  appSecret: #To get application's secret check FACEBOOK.md
