spring:
  datasource:
    url: jdbc:postgresql://jvm-bloggers-db:5432/jvm_bloggers_prod
    username: "ENC(UCI18sY7gx2IG8jU2w3/zcCxE80YLmTfFIjfmiw/IWc=)"
    password: "ENC(paRXsy9M7apHY2C4vvD6Otf4FO40xqdYm/7Ctt+s+58=)"
    driver: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1

endpoints.enabled: false

# Mail Configuration
mailing:
  apiKey: "ENC(MDVhnYiewqWfHfbTepYqnvflkaFRXGDveOVONA24uzWeW74zx1wzB/akhnWxL839)"
  fromEmail: "ENC(UwnuhOY69dp6qFvEDHhl45nGY8iIe+wqm5Yk0pyLS9A=)"
  throttleDelayInSeconds: 180

facebook.api:
  userToken: #User access token can be created as it is described in FACEBOOK.md
  appSecret: #To get application's secret check FACEBOOK.md
